# Generated by Django 6.1 on 2026-08-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Amount owed at the time this customer was digitized, carried over from notebook records.', max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'phone'], name='customers_c_name_ae0c34_idx')],
            },
        ),
    ]
