# Generated by Django 6.1 on 2026-08-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overpaid', 'Overpaid'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=10),
        ),
    ]
