# Generated by Django 6.1 on 2026-08-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='VI Agri Science', max_length=150)),
                ('tagline', models.CharField(blank=True, default='Planting dreams, harvesting life', max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=20, verbose_name='GSTIN')),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('invoice_prefix', models.CharField(blank=True, default='INV', max_length=20)),
                ('default_minimum_stock', models.DecimalField(decimal_places=2, default=10, max_digits=12)),
            ],
            options={
                'verbose_name': 'Business settings',
                'verbose_name_plural': 'Business settings',
            },
        ),
    ]
